### ISSUE TITLE
USB core error import on mac

### ISSUE THREAD

**Issue by rabbadab** [codedance/Retaliation#13]
Hi, 
Maybe this is because i'm new to Python but I can't find a solution to this error I get when I try to run the script.

Traceback (most recent call last):
  File "retaliation.py", line 83, in <module>
    import usb.core
ImportError: No module named usb.core

I have installed the libusb with homebrew on my mac and I have also tried to install python again with homebrew to make new paths.

**Comment by jtheoof** [comment]
I had the same problem as you @rabbadab. All I had to do was to install python using [homebrew](https://github.com/homebrew/homebrew) and then in a new shell:

```
$ python --verion # make sure it is the right python path
Unknown option: --
usage: /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

$ pip install pyusb
Collecting pyusb
  Downloading pyusb-1.0.0b2.tar.gz (57kB)
    100% |████████████████████████████████| 61kB 2.0MB/s
Installing collected packages: pyusb
  Running setup.py install for pyusb
Successfully installed pyusb-1.0.0b2
```

**Comment by codedance** [comment]
Thanks @jtheoof   So you've had to install pyusb with pip?  Do you think a change to the README would help?  e.g.

On a mac system, run the following commands:
```
brew install libusb
pip install pyusb
```

**Comment by jtheoof** [comment]
Yes this is definitely the right steps. However I was not able to pass the kernel extension issues with Yosemite. See #20.

**Comment by jtheoof** [comment]
To more correct @codedance, the install process on os x would be:

```
brew install python # also install pip
brew install libusb 
pip install pyusb
```

**Comment by sebastiannoell** [comment]
Hey there, still having problems here:

`Traceback (most recent call last):
  File "retaliation.py", line 359, in <module>
    main(sys.argv)
  File "retaliation.py", line 355, in main
    run_command(command, value)
  File "retaliation.py", line 235, in run_command
    send_move(UP, value)
  File "retaliation.py", line 223, in send_move
    send_cmd(cmd)
  File "retaliation.py", line 212, in send_cmd
    DEVICE.ctrl_transfer(0x21, 0x09, 0, 0, [0x02, cmd, 0x00,0x00,0x00,0x00,0x00,0x00])
  File "/Library/Python/2.7/site-packages/usb/core.py", line 1034, in ctrl_transfer
    self._ctx.managed_claim_interface(self, interface_number)
  File "/Library/Python/2.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/Library/Python/2.7/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/Library/Python/2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)`

Happens on macOS, High Sierra - got pip, libusb and pyusb installed but ... any ideas?
